about/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "about/about.html"}, name="about"),
    url(r"^terms/$", direct_to_template, {"template": "about/terms.html"}, name="terms"),
    url(r"^privacy/$", direct_to_template, {"template": "about/privacy.html"}, name="privacy"),
    url(r"^dmca/$", direct_to_template, {"template": "about/dmca.html"}, name="dmca"),
    url(r"^what_next/$", direct_to_template, {"template": "about/what_next.html"}, name="what_next"),
)

cambridge/urls.py
# -*- coding: utf-8 -*-

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

from django.conf.urls import url, include

#~ from django.views.generic.simple import direct_to_template
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

from views import *
from forms import *
from models import *


urlpatterns = [
    url(r'^list/$',login_required(RegistrationListView.as_view()), name="cambridge_list"),
    url(r'^list/all$',login_required(RegistrationListViewAll.as_view()), name="cambridge_list_all"),
    url(r'^list/exam/(?P<exam_id>\d+)/$',login_required(RegistrationListViewExam.as_view()), name="cambridge_list_exam"),
    url(r'^excel/$',login_required(RegistrationExcelView.as_view()), name="cambridge_excel"),
    url(r'^excel/exam/(?P<exam_id>\d+)/$',login_required(RegistrationExcelView.as_view()), name="cambridge_excel_exam"),
    url(r'^pay/(?P<pk>\d+)/$',RegistrationPayment,name="cambridge_pay"),
    url(r'^edit/(?P<pk>\d+)/$',
        login_required(UpdateView.as_view(
            model=Registration,
            success_url = '/cambridge/list',
            form_class = RegistrationEditForm,
            template_name='cambridge/registration_edit.html')), name="cambridge_edit"),
    url(r'^delete/(?P<pk>\d+)/$',
        login_required(DeleteView.as_view(
            model=Registration,
            success_url="/cambridge/list/")), name="cambridge_delete"),
    url(r'^view/(?P<pk>\d+)/$', ver, name="cambridge_view"),
    url(r'^print/(?P<pk>\d+)/$', imprimir_cambridge, name="cambridge_imprimir"),
    url(r'^new/(?P<exam_id>\d+)/$',RegistrationExamCreateView.as_view(), name="cambridge_nueva_examen"),
    url(r'^new/$',RegistrationCreateView.as_view(), name="cambridge_nueva"),
    
    #Colegios
    url(r'schools/exam/list/$', login_required(SchoolExamList.as_view()),name="cambridge_schools_exam_list"),
    url(r'schools/exam/(?P<school_name>\w+)/new/$', login_required(SchoolExamCreate.as_view()),name="cambridge_schools_exam_new"),
    url(r'schools/list/$', login_required(SchoolListView.as_view()),name="cambridge_schools_list"),
    url(r'schools/registrations/list/$', login_required(SchoolRegistrationListView.as_view()),name="cambridge_schools_registration_list"),
    url(r'schools/new/(?P<school_name>\w+)/(?P<school_password>\w+)/$', SchoolRegistrationCreateView.as_view(),name="cambridge_schools_new_registration"),
    url(r'schools/new/$', SchoolCreateView.as_view(),name="cambridge_schools_new"),
    url(r'berriotxoa/$', TemplateView.as_view( template_name = 'cambridge/berriotxoa.html' ),name="cambridge_berriotxoa"),
    url(r'schools/fuentefresnedo/$', TemplateView.as_view( template_name =  'cambridge/fuentefresnedo.html' ),name="cambridge_fuentefresnedo"),

    #Venues
    url(r'venue/exam/list/$', login_required(VenueExamList.as_view()),name="cambridge_venues_exam_list"),
    url(r'venue/exam/new/$', login_required(VenueExamCreate.as_view()),name="cambridge_venues_exam_new"),
    url(r'venue/list/$', login_required(VenueListView.as_view()),name="cambridge_venues_list"),
    url(r'venue/registrations/list/$', login_required(VenueRegistrationListView.as_view()),name="cambridge_venues_registration_list"),
    url(r'venue/new/(?P<venue_name>\w+)/$', VenueRegistrationCreateView.as_view(),name="cambridge_venues_new_registration"),
    
    #Linguaskill
    url(r'linguaskill/new/$', LinguaskillRegistrationCreateView.as_view(),name="cambridge_linguaskill_new_registration"),
    url(r'linguaskill/list/$', LinguaskillRegistrationListView.as_view(),name="cambridge_linguaskill_registration_list"),
    

    ## Genericas
    url(r'thanks/$', TemplateView.as_view( template_name = 'cambridge/gracias.html' ),name="cambridge_gracias"),
    url(r'error/$', TemplateView.as_view( template_name = 'cambridge/error.html' ),name="cambridge_error"),
    ##For the exams
    url(r'^exam/list/$',login_required(
		ListView.as_view(model=Exam,template_name='cambridge/exam_list.html')
		), name="cambridge_exam_list"),
    url(r'^exam/delete/(?P<pk>\d+)/$',
        login_required(DeleteView.as_view(
            model=Exam,
            success_url="/cambridge/exam/list/")), name="cambridge_exam_delete"),
    url(r'^exam/new/$', login_required(
        CreateView.as_view(
            model=Exam,
            form_class = ExamForm,
            success_url = '/cambridge/exam/list',
            template_name='cambridge/exam_form.html')), name="cambridge_exam_new"),
    url(r'^exam/edit/(?P<pk>\d+)/$',
        login_required(UpdateView.as_view(
            model=Exam,
            fields = '__all__',
            success_url = '/cambridge/exam/list',
            template_name='cambridge/exam_edit.html')), name="cambridge_exam_edit"),
    url(r'^$', IndexExamList.as_view(),name="cambridge"),
]

matriculas/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^lang/$", TemplateView.as_view(template_name="language.html"), name="language"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^sermepa/", include("sermepa.urls")),
    url(r"^pasarela/", include("pasarela.urls")),
    url(r"^pagosonline/", include("pagosonline.urls")),
    url(r"^cambridge/", include("cambridge.urls")),
    url(r"^hobetuz/", include("hobetuz.urls")),
    url(r"^intensivos/", include("intensivos.urls")),
    url(r"^leveltests/", include("leveltests.urls")),
	url(r"^i18n/", include('django.conf.urls.i18n')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

cambridge/models.py
# -*- coding: utf-8 -*-

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

from django.db import models
from localflavor import generic
from localflavor.es.forms import *
from django.core.mail import EmailMultiAlternatives, send_mail, mail_admins
from django.template.loader import render_to_string

from random import choice
from string import letters
import datetime
import sys

from django.conf import settings
from django.utils import timezone
# favour django-mailer but fall back to django.core.mail
#if "mailer" in settings.INSTALLED_APPS:
#    from mailer import send_mail, mail_admins
#else:
#    from django.core.mail import send_mail, mail_admins

from django.utils.translation import gettext_lazy as _
# Create your models here.

SEXO = (
    (1, _('Male')),
    (2, _('Female')),
)

EXAM_TYPE = (
    (1, _('PB')),
    (2, _('CB')),
    (3, _('FS PB')),
    (4, _('FS CB')),
    (5, _('Linguaskill'))
)

class Level(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    def __unicode__(self):
        try:
            return "[%s] %s-%s"%(self.schoollevel.school,self.name.split(" ")[0],self.price)
	
        except:
            return "%s-%s"%(self.name,self.price)   

class Exam(models.Model):
    exam_type =  models.DecimalField(_('Tipo Examen'),max_digits=1, decimal_places=0,choices=EXAM_TYPE)
    level = models.ForeignKey(Level)
    exam_date =  models.DateField(default=timezone.now)
    registration_end_date =  models.DateField(_('Fecha fin de la matriculación'),default=timezone.now)
    def registrations(self):
        try:
            return self.registration_set.count()
        except:
            return 0   
    def paid_registrations(self):
        try:
            return self.registration_set.filter(paid=True).count()
        except:
            return 0
    def __str__(self):
        return self.__unicode__()
    def __unicode__(self):
        if self.exam_type == 5:
            return "%s"%self.level.name
        try:
            return "[%s] %s %s"%(self.schoollevel,self.get_exam_type_display(),self.exam_date.strftime('%d-%m-%Y'))	
        except:
            try:
                return "%s"%(self.venueexam)	
            except:
                return "%s %s %s"%(self.level,self.get_exam_type_display(),self.exam_date.strftime('%d-%m-%Y'))

class School(models.Model):
    name = models.CharField(_('Name'),max_length=50)
    description = models.CharField(_('Description'),max_length=100,default="")
    password = models.CharField(_('Password'),max_length=50)
    def __unicode__(self):
        return self.name
    def exam_count(self):
        return self.schoolexam_set.all().count()
    def registration_count(self):
        total=0
        for e in self.schoolexam_set.all():
            total = total + e.registration_set.all().count()
        return total

class Venue(models.Model):
    name = models.CharField(_('Name'),max_length=50)
    description = models.CharField(_('Description'),max_length=100,default="")
    password = models.CharField(_('Password'),max_length=50)
    def __unicode__(self):
        return self.name
    def exam_count(self):
        return self.venueexam_set.all().count()
    def registration_count(self):
        total=0
        for e in self.venueexam_set.all():
            total = total + e.registration_set.all().count()
        return total

class SchoolLevel(Level):
    school = models.ForeignKey(School)

class SchoolExam(Exam):
    school = models.ForeignKey(School)
    def __unicode__(self):
        return "%s %s %s"%(self.level.__unicode__(),self.get_exam_type_display(),self.exam_date.strftime('%d-%m-%Y'))

class VenueExam(Exam):
    venue = models.ForeignKey(Venue)
    def __unicode__(self):
        return "[%s]%s %s %s"%(self.venue,self.level.__unicode__(),self.get_exam_type_display(),self.exam_date.strftime('%d-%m-%Y'))

class Registration(models.Model):
    exam = models.ForeignKey(Exam,limit_choices_to = {'registration_end_date__gte': datetime.date.today()})
    password = models.CharField(_('Password'),max_length=6,blank=True,editable=False)
    name = models.CharField(_('Nombre'),max_length=50)
    surname = models.CharField(_('Apellido(s)'),max_length=100)
    address = models.CharField(_('Dirección'),max_length=100)
    location = models.CharField(_('Localidad'),max_length=100)
    postal_code = models.DecimalField(_('Código Postal'),max_digits=6, decimal_places=0)
    sex = models.DecimalField(_('Sexo'),max_digits=1, decimal_places=0,choices=SEXO)
    birth_date = models.DateField(_('Fecha Nacm. DD-MM-AAAA'), help_text=_('Formato: DD-MM-AAAA(dia-mes-año)'))
    #dni = models.CharField(max_length=9,blank=True,help_text=_('Introduce el DNI completo con la letra sin espacios ni guiones'))
    telephone = models.CharField(_('Teléfono'),max_length=12)
    email = models.EmailField()
    eide_alumn = models.BooleanField(_('Alumno EIDE'), default="False", blank=True, help_text=_('Haz click en el check si eres alumno/a de EIDE. En caso contrario rellena porfavor la siguiente casilla.'))
    centre_name = models.CharField(_('Nombre del Centro'),max_length=100, blank=True) 
    registration_date = models.DateField(auto_now_add=True)
    paid = models.BooleanField(_('Pagada'),default=False)
    accept_conditions = models.BooleanField(_('He leído y acepto las condiciones generales.'),default=True,blank=True)
    accept_photo_conditions = models.BooleanField(_('Doy mi consentimiento expreso para que mi imagen pueda ser utilizada en la página Web o en redes sociales del centro así como en todo el material publicitario que pueda utilizar.'), help_text=_('Debes aceptar las condiciones de la la toma de foto para poder matricularte.'),default=True,blank=True)
    minor = models.BooleanField(_('El candidato es menor de edad y yo soy su padre/madre o tutor legal.'),default=False,blank=True)
    tutor_name = models.CharField(_('Nombre de padre/madre o tutor.'),max_length=50,blank=True)
    tutor_surname = models.CharField(_('Apellido(s) del padre/madre o tutor.'),max_length=100,blank=True)
    def send_confirmation_email(self):
        ##Para el alumno
        subject = _("Te has matriculado para un examen Cambridge en EIDE")        
        html_content = u"""
<div class="well">
    Acaba de realizar una solicitud de matrícula para: <br />
    %s 
</div>
<div class="well">
    <h1>Pago de la matrícula</h1>
    La matrícula se hará efectiva una vez se haya recibido el pago. Puede hacer el pago en la siguiente dirección: <a href="http://matricula-eide.es/%s">http://matricula-eide.es/%s</a>
</div>"""%(self.exam,self.generate_payment_url(),self.generate_payment_url())      
        message_body = html_content
        ##send_mail(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
        msg = EmailMultiAlternatives(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
        msg.attach_alternative(html_content, "text/html")
        ##msg.content_subtype = "html"
        #msg.send()         
        ### Para los admins
        subject = "Hay una nueva matricula (sin pagar) para cambridge %s"%self.exam
        message_body = u"""Se ha dado de alta una nueva matricula para el examen %s. 
Los datos son del alumno son: 
    Nombre: %s
    Apellidos: %s
    Telefono: %s
    e-mail: %s
"""%(self.exam,self.name,self.surname,self.telephone,self.email)
        mail_admins(subject, message_body)
    def send_paiment_confirmation_email(self):
        try:
            ls = LinguaskillRegistration.objects.get(id=self.id)
            exam_date=ls.proposed_date
        except:
            exam_date=self.exam.exam_date
        subject = "Se ha confirmado el pago de la matricula para el examen %s"%self.exam
        html_content=u"""<html><body>
        <h2>CONFIRMACIÓN DE MATRÍCULA</h2>
<p>Se ha matriculado para el examen <b> %s </b>. Tras el cierre del periodo de matriculación se le enviará el COE (Confirmation of Entry) 
con las fechas y horas del examen escrito y oral a la dirección de e-mail que ha proporcionado el candidato en la 
hoja de matrícula. Si dos semanas antes de la fecha del examen el candidato no ha recibido el COE, es su responsabilidad 
el ponerse en contacto con EIDE y solicitar el COE. EIDE no se responsabiliza del extravío o no recepción del mismo y no 
asume ninguna responsabilidad por cualquier problema derivado del desconocimiento de la fecha, horario y lugar del examen 
y se reserva el derecho de no admitir a candidatos que lleguen tarde.</p>

<p>Es responsabilidad del candidato llegar al lugar del examen con 15 minutos de antelación. Los candidatos deben traer un 
DNI o pasaporte que atestigüe su identidad en cada examen (escrito y oral).</p>
        """%(self.exam)
	#html_content= html_content+render_to_string('cambridge/legal.html')
        html_content= html_content+u"""</body></html>"""
        message_body = html_content
        ##send_mail(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
        #msg = EmailMultiAlternatives(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
        #msg.attach_alternative(html_content, "text/html")
        ##msg.content_subtype = "html"
        #msg.send()

cambridge/templates/cambridge/berriotxoa.html
{% extends "site_base.html"%}

{% load i18n %}

{% block body %}
<div class="hero-unit">

    <h2>{% trans "Matrícula para Exámenes Cambridge English en Berri-Otxoa" %}</h2>
    <br />
    <p class="pagination-centered" >
		<a class="btn primary large" href="/cambridge/schools/new/berriotxoa/berriotxoacambridge2016/">{% trans "Matricúlate" %}</a>
	</p>
</div>
{% endblock %}

cambridge/templates/cambridge/exam_confirm_delete.html
{% extends "site_base.html"%}
{% load i18n %}
{% block body %}
    <h1>{% trans "Delete Exam" %}{{object}}</h1>

	<form action="{% url 'cambridge_exam_delete' object.id %}" method="post">{% csrf_token %}
	¿Seguro que desas borrar exámen {{object}} ?
    <br />
	<input class="btn submit" type="submit" value="Eliminar"/>
	<a class="btn" href="{% url 'cambridge_exam_list' %}">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

cambridge/templates/cambridge/exam_edit.html
{% extends "site_base.html"%}
{% load i18n %}

{% block body %}
  <script>
  $(document).ready(function() {
	  $("#id_exam_date").datepicker({format: "yyyy-mm-dd"});
	  $("#id_registration_start_date").datepicker({format: "yyyy-mm-dd"});
  });
  </script>
    <h1>{% trans "Exam " %}{{object}}</h1>
	<form action="{% url 'cambridge_exam_edit' object.id %}" method="post">{% csrf_token %}
      {{ form.as_p }}
	<input class="submit btn-form" type="submit" value="{% trans 'Save' %}" />
	<a class="btn" href="{% url 'cambridge_exam_list' %}">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

cambridge/templates/cambridge/exam_list.html
{% extends "site_base.html"%}

{% load i18n %}

{% block body %}

<h1>{% trans "Cambridge Exam List" %}</h1>

<table class="table">
    <thead>
        <tr>
        <td>{% trans "Level" %}</td>
        <td>{% trans "Tipo" %}</td>
        <td>{% trans "Date" %}</td>
        <td>{% trans "Cierre de la matrícula" %}</td>
        <td>{% trans "Price" %}</td>
        <td>{% trans "Registration URL" %}</td>
        <td>{%trans "Matrículas" %}</td>
        <td>{%trans "Paid Registrations" %}</td>
        <td>{%trans "Delete" %}</td>
        </tr>
    </thead>
    <tbody>
    {% for exam in object_list %}
    <tr>
    <td><a href="{% url 'cambridge_exam_edit' exam.id %}">{{ exam.level }}</a></td>
    <td>{{ exam.get_exam_type_display }}</a></td>
    <td>{{ exam.exam_date }}</td>
    <td>{{ exam.registration_end_date }}</td>
    <td>{{ exam.level.price }}</td>
    <td><a href="{% url 'cambridge_nueva_examen' exam.id %}">Url Matrícula</a></td>
    <td>{{ exam.registrations }}</td>
    <td> <a href="{% url 'cambridge_list_exam' exam.id %}"><i class="fa fa-list" aria-hidden="true"></i> {{ exam.paid_registrations }}</a></td>
    <td><a href="{% url 'cambridge_exam_delete' exam.id %}">Eliminar</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<!-- <a class="btn" href="{% url 'cambridge_exam_new' %}">{% trans "New" %}	</a>-->
{% endblock %}

cambridge/templates/cambridge/linguaskill_registration_form.html
{% extends "site_base.html"%}
{% load i18n %}
{% load bootstrap %}

{% block extra_body %}
<script>
	function comprobar_condiciones() {
        comprobar_aceptacion();
	}
	function comprobar_aceptacion() {
		console.log("Han hecho click en el check de las condiciones");
        acepta = false ;
        if ($("#id_accept_conditions").is(":checked"))
		{
		    console.log("Condiciones generales aceptadas");
			acepta = true;
		}
		if (acepta) {
		    console.log("Dice que las acepta");
		    $("#send_form").prop('disabled', false);
		    console.log("Ocultamos el aviso");
		    $("#aviso_condiciones").hide();
		}
        else {
            //Deshabilitamos el envio hasta que acepten las condiciones
            console.log("Dice que NO las acepta");
            $("#send_form").prop('disabled', true);
            console.log("Mostramos el aviso");
            $("#aviso_condiciones").show();
        }
    }
	
    $(document).ready(function() {
	    //$("#id_birth_date").datepicker({format: "dd-mm-yyyy",weekStart: 1});
	    $("#normativa_general").hide();
        //Comprobamos si se puede enviar
	    comprobar_condiciones();
        $("#id_centre_name").prop('disabled', false);
        //Control de la aceptación de las condiciones:
	    $("#id_exam").change(comprobar_condiciones);
        $("#id_accept_conditions").change(comprobar_aceptacion);
	    
        //Control del Centre Name 
        $("#id_eide_alumn").change(function() {
            console.log("Han hecho click en el check de alumno de eide");
            if ($("#id_eide_alumn").is(":checked")) {
                console.log("Dice que es alumno de EIDE, desactivamos el input centrename");
                $("#id_centre_name").prop('disabled', true);
            }
            else {
                console.log("Dice que NO es alumno de EIDE, activamos el input centrename");
                $("#id_centre_name").prop('disabled', false);
            }
        });            
    });
    </script>
{% endblock %}

{% block body %}
<h1>{% trans "Matricúlate para un Exámen Cambridge Linguaskill" %}</h1>

<div class="alert-message block-message error">


<span class="label label-info"> Atención! </span>La única forma de pago aceptada es <b>vía tarjeta de crédito/débito</b>.<br />
<!-- <span class="label label-info"> Atención! </span>Los exámenes serán presenciales y se realizarán en las instalaciones de EIDE. -->

</div>

<div class="alert-mesagge block-message alert">
<p>
    Se le informa al interesado que conforme a lo previsto en el RGPD de 27 de abril de 2016 
    y la LO 3/2018, de 5 de diciembre (LOPDGDD) el Responsable de este tratamiento de datos 
    personales es Escuelas Internacionales para la Educación y el Desarrollo Eide, S.L., 
    (CIF: B48474647), Genaro Oraá Kalea, Santurce (48980, Bizkaia); Tel.: 944937005; 
    email: <a href="mailto://eide@eide.es">eide@eide.es</a>

    Las finalidades del tratamiento de datos versarán sobre la gestión genérica del examen 
    Cambridge English, incluyendo el proceso de matrícula y cobro de tasas, organización 
    de la sesión del examen, para comunicarnos con el candidato, o con sus representantes 
    legales debidamente acreditados a tal efecto sobre cuestiones relacionadas con el examen 
    contratado y/o facilitar condiciones especiales para la realización del examen, cuando 
    ello sea necesario. Dichos datos serán conservados durante el plazo mínimo necesario 
    establecido para la oportuna gestión y tramitación de la prueba.
    
    Dichos datos serán en su caso cedidos única y exclusivamente a los organismos competentes 
    encargados del proceso administrativo y de ejecución del examen, así como otros 
    supuestos establecidos en la ley.
    
    Podrá ejercitar los derechos de acceso, rectificación, supresión, limitación, portabilidad 
    y oposición dirigiéndose a Escuelas Internacionales para la Educación y el Desarrollo 
    Eide, S.L. con dirección en Genaro Oraá Kalea, Santurce (48980, Bizkaia), o enviando una 
    comunicación con referencia RGPD/LOPDGDD al email de contacto 
    <a href="mailto://eide@eide.es">eide@eide.es</a>.
</p>
</div>

<div class="row">
    <div class="span14">
		
	 <form method="post" class="form-horizontal" >{% csrf_token %}


	<p>En el siguiente desplegable, selecciona el examen.</p>
    <!--
    <ul>
	    <li>Niveles de Exámenes: <b>KET</b>: A2 – <b>PET</b>: B1– <b>FCE</b>: First Certificate. B2. – <b>CAE</b>: Advanced. C1. – <b>CPE</b>: Proficiency. C2.</li>
	    <li>Tipo de examen: Ordinario (no llevan ninguna sigla) - <b>FS</b>: For Schools, exámenes para menores de 18 - <b>YLE</b>: Exámenes Young Learners, para niños/as de primaria.</li>
	    <li>Formato: <b>CB</b>: Computer Based. Exámenes en ordenador – <b>PB</b>: Paper Based. Exámenes ordinarios en papel.</li>
    </ul>
    -->
	{{ form|bootstrap }}
    </div> 
</div>


<div id="legal_general" class="row">
    <div class="span14">
	{% include "cambridge/linguaskill_legal.html" %}
	<div>
	    He leído y acepto las condiciones generales. <input type="checkbox" id="id_accept_conditions" name="accept_conditions">
        </div>
	
    </div> 
</div>
<hr />

<div class="row">
    <div class="span12">    
	<div class="well" id="aviso_condiciones">
	    {% trans "<b>¡Atención!.</b> Todavía no has aceptado las condiciones. Si no aceptas las condiciones generales y las condiciones de la toma de foto no podrás enviar la matrícula." %}
	</div>
	<input id="send_form" class="btn btn-primary pull-right" type="submit" value="{% trans 'Submit' %}" />
    </div> 
</div> 

{% endblock %}

cambridge/templates/cambridge/school_exam_form.html
{% extends "site_base.html"%}
{% load i18n %}

{% block body %}
  <script>
  $(document).ready(function() {
	  $("#id_exam_date").datepicker({format: "dd-mm-yyyy",weekStart: 1});
	  $("#id_registration_end_date").datepicker({format: "dd-mm-yyyy",weekStart: 1});
  });
  </script>

    <h1>{% trans "New Exam for " %}{{school_name}}</h1>

	<form class="form-horizontal" action="{% url 'cambridge_schools_exam_new' school_name %}" method="post">{% csrf_token %}
	    {% load bootstrap %}
	    {{ form|bootstrap }}
	    <input class="submit btn-form" type="submit" value="{% trans 'Save' %}" />
	    <a class="btn" href="{% url 'cambridge_exam_list' %}">{% trans "Cancel" %}</a>
	</form>
{% endblock %}