about/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "about/about.html"}, name="about"),
    url(r"^terms/$", direct_to_template, {"template": "about/terms.html"}, name="terms"),
    url(r"^privacy/$", direct_to_template, {"template": "about/privacy.html"}, name="privacy"),
    url(r"^dmca/$", direct_to_template, {"template": "about/dmca.html"}, name="dmca"),
    url(r"^what_next/$", direct_to_template, {"template": "about/what_next.html"}, name="what_next"),
)

inscripciones/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic.simple import direct_to_template

from views import *

urlpatterns = patterns('inscripciones/',
    url(r'^list/$',login_required(RegistrationListView.as_view()), name="inscripciones_list"),
    url(r'^new/$',RegistrationCreateView.as_view(), name="inscripciones_nueva"),
    url(r'^edit/(?P<pk>\d+)/$',login_required(RegistrationUpdateView.as_view()), name="inscripciones_edit"),
    url(r'^delete/(?P<pk>\d+)/$', login_required(RegistrationDeleteView.as_view()), name="inscripciones_delete"),
    url(r'^view/(?P<pk>\d+)/$', login_required(RegistrationDetailView.as_view()), name="inscripciones_detalle"),
    url(r'thanks/$', direct_to_template, {'template': 'inscripciones/gracias.html' },name="inscripciones_gracias"),
    url(r'^/?$', direct_to_template,{'template': 'portada.html' },name="inscripciones"),
)

matriculas/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^lang/$", TemplateView.as_view(template_name="language.html"), name="language"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^sermepa/", include("sermepa.urls")),
    url(r"^pasarela/", include("pasarela.urls")),
    url(r"^pagosonline/", include("pagosonline.urls")),
    url(r"^cambridge/", include("cambridge.urls")),
    url(r"^hobetuz/", include("hobetuz.urls")),
    url(r"^intensivos/", include("intensivos.urls")),
    url(r"^leveltests/", include("leveltests.urls")),
	url(r"^i18n/", include('django.conf.urls.i18n')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

inscripciones/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import gettext_lazy as _
import datetime 
from django.conf import settings
#Para la autogneración de passwd
from random import choice
from string import letters
#Para el envio del mail de confirmacion
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

# favour django-mailer but fall back to django.core.mail
if "mailer" in settings.INSTALLED_APPS:
    from mailer import send_mail, mail_admins
else:
    from django.core.mail import send_mail, mail_admins


SEXO = (
    (1, _('Male')),
    (2, _('Female')),
)

CURSO = (
    (1, _('Inglés nivel A2')),
    (2, _('Inglés nivel B2')),
    (3, _('Inglés nivel C1')),
)

ENGLISH_LEVEL = (
    (1, _('A1')),
    (2, _('A2')),
    (3, _('B1')),
    (4, _('B2.1')),
    (5, _('B2.2')),
    (6, _('C1.1')),
    (7, _('C1.2')),
    (8, _('C2'))
)

class Registration(models.Model):
    course = models.DecimalField('¿En que curso estás interesado?',max_digits=1, decimal_places=0,choices=CURSO)
    password = models.CharField(_('Password'),max_length=6,blank=True,editable=False)
    name = models.CharField(_('Nombre (*)'),max_length=50)
    surname = models.CharField(_('Apellido(s) (*)'),max_length=100)
    #~ address = models.CharField(_('Address'),max_length=100)
    #~ location = models.CharField(_('Location'),max_length=100)
    birth_date = models.DateField(_('Birth Date'),help_text=_('Formato: AAAA-MM-DD(año-mes-día)'))
    telephone = models.CharField('Tel. Fijo (*)',max_length=12)
    email = models.EmailField('Email (*)')
    registration_date = models.DateField(default=datetime.date.today, auto_now_add=True)
    accept_conditions = models.BooleanField(_('Accept the conditions'), help_text=_('You must accept the conditions to register'),default=True,blank=True)
    paid = models.BooleanField(_('Paid'),default=False)
    estudios_superiores = models.BooleanField('¿Tienes titulación de ESO o Superior?')
    english_level = models.DecimalField('¿Cuál es tu nivel de Inglés?',max_digits=1, decimal_places=0,choices=ENGLISH_LEVEL)
    english_qualification = models.CharField('¿Tienes titulación oficial de Inglés?¿Cual?',max_length=25)
    def get_absolute_url(self):
        return '/inscripciones/edit/%d/'%self.id
    def __unicode__(self):
        return u"%s-%s"%(self.id,self.email)
    def registration_name(self):
        return self.__unicode__()
    def send_confirmation_email(self):
        ##Para el alumno
        subject = "Has solicitado un curso en EIDE"        
        html_content = u"""
<html>
<head>
        <link rel="stylesheet" href="https://matricula-eide.es/site_media/static/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://matricula-eide.es/site_media/static/css/extra.css">
</head>
<body>
<div class="well">
    <p>Buenas</p>
    Acaba de realizar una solicitud de curso para: <br />
    %s <br>
    <p>Pronto nos pondremos en contacto desde EIDE para formalizar la inscripción.</p>
    <p>Gracias.</p>
</div>
<div class="well">
<p></p>
</div>
</body>
</html>
"""%(self.get_course_display())
        
        message_body = html_content
        ##send_mail(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
        msg = EmailMultiAlternatives(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
        msg.attach_alternative(html_content, "text/html")
        ##msg.content_subtype = "html"
        msg.send()
        
        ##Para el secretaria        
        subject = "[EIDE] Matricula curso"
        payload = {'registration': self}
        
        html_content = render_to_string('inscripciones/registration_detail.html', payload)
        message_body = html_content
        ##send_mail(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
        msg = EmailMultiAlternatives(subject, message_body, settings.DEFAULT_FROM_EMAIL, ["moebius1984@gmail.com","secretaria@eide.es"])
        msg.attach_alternative(html_content, "text/html")
        ##msg.content_subtype = "html"
        msg.send()

    
        
#~ def Curso(models.model):
    #~ name = models.CharField(_('Nombre (*)'),max_length=50)
    #~ description = models.CharField(_('Descripción (*)'),max_length=500)
    #~ price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    #~ def __unicode__:
        #~ return self.name

inscripciones/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import ModelForm
from models import *
from django.forms.models import inlineformset_factory
from django.forms.extras.widgets import SelectDateWidget
from django.contrib.localflavor.es.forms import *
from django.contrib.admin import widgets                                       
from django.utils.translation import gettext_lazy as _

class RegistrationForm(ModelForm):
    telephone = ESPhoneNumberField(label=_("Teléfono (*)"))
    class Meta:
        model = Registration
        exclude = ('paid','accept_conditions')
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.format = '%Y-%m-%d'
        self.fields['birth_date'].input_formats = ['%Y-%m-%d']

class RegistrationEditForm(ModelForm):
    telephone = ESPhoneNumberField(label=_("Teléfono"))
    class Meta:
        model = Registration
    def __init__(self, *args, **kwargs):
        super(ModelForm, self).__init__(*args, **kwargs)
        self.fields['birth_date'].widget.format = '%Y-%m-%d'
        self.fields['birth_date'].input_formats = ['%Y-%m-%d']

inscripciones/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import DetailView, ListView, CreateView, UpdateView, View, DeleteView
from django.views.generic.edit import ModelFormMixin

from models import *
from forms import *

class RegistrationDetailView(DetailView):
    model=Registration
    template_name='inscripciones/detalle.html'

class RegistrationDeleteView(DeleteView):
    model=Registration
    success_url = '/inscripciones/list/'

class RegistrationUpdateView(UpdateView):
    model=Registration  
    success_url = '/inscripciones/list/'

class RegistrationPayment(DetailView):
    model=Registration
    template_name='inscripciones/payment.html'
    
class RegistrationCreateView(CreateView):
    model = Registration
    form_class = RegistrationForm
    #~ fields = "__all__"
    #~ exclude = ["paid", "registration_date"]
    template_name='inscripciones/registration_form.html'
    #~ def get_context_data(self, **kwargs):
        #~ context = super(RegistrationCreateView, self).get_context_data(**kwargs)
        #~ context['lista_inscripciones'] = Intensivo.objects.all()
        #~ return context
    def get_success_url(self):
        return '/inscripciones/thanks/'
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()    
        self.object.password = ''.join([choice(letters) for i in xrange(6)])
        self.object.send_confirmation_email()
        return super(ModelFormMixin, self).form_valid(form)
def RegistrationExcelView(request):
    objs = Registration.objects.all()
    return ExcelResponse(objs)

class RegistrationListView(ListView):
    model = Registration
    template_name='inscripciones/lista.html'

inscripciones/templates/inscripciones/gracias.html
{% extends "site_base.html"%}

{% load i18n %}

{% block body %}
Gracias. Pronto recibirá información de EIDE en relación a su matrícula.
{% endblock %}

inscripciones/templates/inscripciones/legal.html
<div class="alert-mesagge block-message alert">
<p>En cumplimiento con los establecido en la Ley Orgánica 15/99 de Protección de Datos de Carácter Personal, los datos de carácter personal que nos facilite serán utilizados en la forma y con las limitaciones y derechos que recoge la Ley y pasarán a formar parte de un fichero propiedad de EIDE. Estos datos son necesarios para la gestión de los cursos de Hobetuz. Al facilitarnos sus datos personales consiente el tratamiento informatizado o no de los mismos por EIDE para los fines anteriormente citados.</p>
</div>

inscripciones/templates/inscripciones/registration_detail.html
{% extends "site_base.html"%}

{% load i18n %}

{% block body %}

<h1>Inscripción para {{ registration.get_course_display }}</h1>

<table class="table">
	<tr>
		<td><b>Nivel de Ingles actual</b></td><td>{{registration.get_english_level_display}}</td>
	</tr>
	<tr>
		<td><b>Titulación</b></td><td>{{registration.english_qualification}}</td>
	</tr>	
	<tr>
		<td><b>Estudios superiores</b></td><td>{{registration.estudios_superiores|yesno:"sí,no,quizá"}}</td>
	</tr>	
	
	<tr>
		<td><b>Nombre y Apellidos</b></td><td>{{ registration.name }} {{ registration.surname }}</td>
	</tr>
	<tr>
		<td><b>Fecha registro</b></td><td> {{registration.registration_date}} </td>
	</tr>
<!--
	<tr>
		<td><b>Dirección</b></td><td>{{registration.location}}</td>
	</tr>
-->
	<tr>
		<td><b>Fecha Nacimiento</b></td><td>{{registration.birth_date}}</td>
	</tr>
	<tr>
		<td><b>Email</b></td><td>{{registration.email}}</td>
	</tr>
	<tr>
		<td><b>Teléfono</b></td><td>{{registration.telephone}}</td>
	</tr>
	

</table>

<a class="btn primary" href="{% url inscripciones_list %}">Volver</a>
<button class="button" href="">Imprimir</button>

{% endblock %}

inscripciones/templates/inscripciones/registration_form.html
{% extends "site_base.html"%}
{% load i18n %}
{% load bootstrap_tags %}

{% block extra_head %}

<script>
	function comprobar_aceptacion() {
		console.log("Comprobamos de las condiciones");
		acepta = false;
		if ($("#id_accept_conditions").is(":checked"))
		{
		    console.log("Condiciones generales aceptadas");
			acepta = true;
		}
		if (acepta) {
		    console.log("Dice que las acepta");
		    $("#send_form").prop('disabled', false);
		    console.log("Ocultamos el aviso");
		    $("#aviso_condiciones").hide();
		}else {
		    //Deshabilitamos el envio hasta que acepten las condiciones
			console.log("Dice que NO las acepta");
			$("#send_form").prop('disabled', true);
		    console.log("Mostramos el aviso");
		    $("#aviso_condiciones").show();
		}
    }
	$(document).ready(function() {
		//~ $("#id_birth_date").datepicker({format: "dd-mm-yyyy",weekStart: 1});
    	$("#normativa_general").hide();
		//Comprobamos si se puede enviar
    	comprobar_aceptacion();
        	
		//Control de la aceptación de las condiciones:
		$("#id_accept_conditions").change(comprobar_aceptacion);
	    	
            
	});            
</script>

{% endblock%}

{% block body %}
<div class="row">
    <div class="span12">		
	<h1>{% trans "Inscripción a un curso" %}</h1>
	<div>
	    {{ curso.description }}
	    
	    <h3>SOLICITUD INSCRIPCIÓN PARA CURSOS GRATUITOS PARA MENORES DE 30 AÑOS</h3>
	    <p>Subvencionados por el Servicio Público de Empleo Estatal</p>
	    <p>Actualmente, está previsto que se impartan los siguientes cursos:</p>
	    <ul>
	    <li>Inglés nivel A2 para menores de 30 años (150 horas).  Del 12 Abril-24 al Junio de 09.00 a 12.00. Requisitos de idioma: nivel de inglés B1.</li>
	    <li>Inglés nivel B2 para menores de 30 años (240 horas). Del 5 de Abril al 30 de Junio de 09.00 a 13.15. Requisitos de idioma: nivel de inglés B2.</li>
	    <li>Inglés nivel C1 para menores de 30 años (240 horas). De Octubre a Diciembre de 2016, 4 horas por día en horario de mañana de Lunes a Viernes. Requisitos de idioma: nivel de inglés C1.</li>
	    </ul>
	    <p>NOTA: Las fechas y horarios pueden sufrir variaciones.</p>
	    <p>REQUISITOS MÍNIMOS DE ESTUDIOS: ESO</p>
	    <p>Si está interesado/a rellene los siguientes datos y nos pondremos en contacto con usted.</p>
	</div>
	<form action="" method="post" class="form-horizontal" >{% csrf_token %}
	{{ form|as_bootstrap }}
    </div> 
</div>
<!-- Legal -->
<div id="legal_general" class="row">
    <div class="span14">
        {% include "inscripciones/legal.html" %}
        <div>
            ¿Aceptas las condiciones? <input type="checkbox" id="id_accept_conditions" name="accept_conditions">
        </div>        
    </div> 
</div>
<!-- Legal -->

<!-- Aviso y envio -->
<div class="row">
    <div class="span12">    
	<div class="well" id="aviso_condiciones">
	    {% trans "<b>¡Atención!.</b> Todavía no ha aceptado las condiciones. Si no acepta las condiciones generales no podrá enviar la matrícula." %}
	</div>
	<input id="send_form" class="btn primary pull-right" type="submit" value="Enviar" />
    </div> 
</div> 
<!-- Aviso y envio -->
{% endblock %}

inscripciones/templates/inscripciones/registration_list.html
{% extends "site_base.html"%}

{% load i18n %}

{% block body %}

<!-- 
<p>
<a class="btn btn-success" href="#">Bajar como fichero excel</a></li>
</p>
-->
<h2>Lista de Inscripciones</h2>
<table class="table">
    <thead>
        <tr>
	    <td>{% trans "Nombre" %}</td>
            <td>Curso</td>
            <td>Nivel Actual</td>
	    <td>Titulación</td>
	    <td>Estudios superiorioes</td>
            <td>Email</td>
            <td>Telefono</td>
            <td>Fecha Nac.</td>
<!--
            <td>Acciones</td>
-->
        </tr>
    </thead>
    <tbody>
        {% for matricula in object_list %}
        <tr>
            <td> <a href="{% url inscripciones_detalle matricula.id %}">{{ matricula.surname }},{{ matricula.name }}</a></td>
	    <td>{{ matricula.get_course_display}}</td>
	    <td>{{ matricula.get_english_level_display}}</td>
	    <td>{{ matricula.english_qualification}}</td>
	    <td>{{ matricula.estudios_superiores|yesno:"sí,no,quizá" }}</td>
	    <td><a href="mailto:{{ matricula.email}}">{{ matricula.email}}</a></td>
	    <td>{{ matricula.telephone}}</td>
	    <td>{{ matricula.birth_date}}</td>
<!--
            <td>
		<a class="btn primary small" href="{% url inscripciones_detalle matricula.id %}">Detalles</a>
		<a class="btn small" href="{% url inscripciones_edit matricula.id %}">Editar</a> 
                
                <a class="btn small" href="{% url inscripciones_delete matricula.id %}">{% trans "Delete" %}</a>
            </td>
-->
        </tr>
    {% endfor %}
    </tbody>
</table>
	<a class="btn primary pull-left" href="{% url inscripciones_nueva %}" >Nueva matricula</a> 
{% endblock %}