about/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "about/about.html"}, name="about"),
    url(r"^terms/$", direct_to_template, {"template": "about/terms.html"}, name="terms"),
    url(r"^privacy/$", direct_to_template, {"template": "about/privacy.html"}, name="privacy"),
    url(r"^dmca/$", direct_to_template, {"template": "about/dmca.html"}, name="dmca"),
    url(r"^what_next/$", direct_to_template, {"template": "about/what_next.html"}, name="what_next"),
)

hobetuz/urls.py
# -*- coding: utf-8 -*-

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView,DetailView, ListView, CreateView, UpdateView, DeleteView

from views import *
from forms import *
from models import *


urlpatterns = [
    url(r'^new/2019/$',Registration2019CreateView.as_view(), name="hobetuz_nueva_2019"),
    url(r'^view/2019/(?P<pk>\d+)/$', login_required(Registration2019DetailView.as_view()), name="hobetuz_2019_view"),
    url(r'^list/2019/$',login_required(Registration2019ListView.as_view()), name="hobetuz_list_2019"),
    #url(r'^list/$',RegistrationListView.as_view(), name="hobetuz_list"),
    #url(r'^new/$',RegistrationCreateView.as_view(), name="hobetuz_nueva"),
    #url(r'^excel/$',RegistrationExcelView, name="hobetuz_excel"),
    #url(r'^edit/(?P<pk>\d+)/$',login_required(RegistrationUpdateView.as_view()), name="hobetuz_edit"),
    #url(r'^delete/(?P<pk>\d+)/$',
    #    login_required(DeleteView.as_view(
    #        model=Registration,
    #        success_url="/hobetuz/list/")), name="hobetuz_delete"),
    #url(r'^view/(?P<pk>\d+)/$', ver, name="hobetuz_view"),
    #url(r'^print/(?P<pk>\d+)/$', imprimir_hobetuz, name="hobetuz_imprimir"),
    
    ## Genericas
    url(r'thanks/$', TemplateView.as_view( template_name='hobetuz/gracias.html' ),name="hobetuz_gracias"),
    #~ ##Para los cursos
    #url(r'^curso/list/$',login_required(CursoList.as_view()), name="hobetuz_curso_lista"),
    #url(r'^curso/delete/(?P<pk>\d+)/$',
    #    login_required(DeleteView.as_view(
    #        model=Curso,
    #        success_url="/hobetuz/curso/list/")), name="hobetuz_curso_delete"),
    #url(r'^curso/new/$', login_required(
    #    CreateView.as_view(
    #        model=Curso,
    #        form_class = CursoForm,
    #        success_url = '/hobetuz/curso/list',
    #        template_name='hobetuz/curso_form.html')), name="hobetuz_curso_nuevo"),
    #url(r'^curso/edit/(?P<pk>\d+)/$',
    #    login_required(UpdateView.as_view(
    #        model=Curso,
    #        success_url = '/hobetuz/curso/list',
    #        template_name='hobetuz/curso_edit.html')), name="hobetuz_curso_edit"),
    #url(r'^/?$', HobetuzPortada.as_view(),name="hobetuz"),
]

matriculas/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^lang/$", TemplateView.as_view(template_name="language.html"), name="language"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^sermepa/", include("sermepa.urls")),
    url(r"^pasarela/", include("pasarela.urls")),
    url(r"^pagosonline/", include("pagosonline.urls")),
    url(r"^cambridge/", include("cambridge.urls")),
    url(r"^hobetuz/", include("hobetuz.urls")),
    url(r"^intensivos/", include("intensivos.urls")),
    url(r"^leveltests/", include("leveltests.urls")),
	url(r"^i18n/", include('django.conf.urls.i18n')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

hobetuz/models.py
# -*- coding: utf-8 -*-

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

from django.db import models
from localflavor import generic
from localflavor.es.forms import *
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.template.loader import render_to_string

from random import choice
from string import letters
import datetime

from django.conf import settings

# favour django-mailer but fall back to django.core.mail
if "mailer" in settings.INSTALLED_APPS:
    from mailer import send_mail, mail_admins
else:
    from django.core.mail import send_mail, mail_admins

from django.utils.translation import gettext_lazy as _
# Create your models here.

SEXO = (
    (1, _('Male')),
    (2, _('Female')),
)

SITUACION_LABORAL = (
    (1, _('Desempleado/a')),
    (2, _('Ocupado/a')),
    (3, _('Funcionario/a')),
)

CURSOS_2019 = (
	('cocina', 'Cocina'),
	('ingles','Inglés'),
)

TITULACION = (
    (1, _('Sin titulación')),
    (2, _('Graduado Escolar o ESO')),
    (3, _('Bachillerato, COU o similar')),
    (4, _('Grado, Licenciatura o Diplomatura')),
    (5, _('Certificado de Profesionalidad en Turismo y Hostelería de Nivel 1')),
    (6, _('Certificado de Profesionalidad en Turismo y Hostelería de Nivel 2 o 3')),
    (7, _('Ciclo Grado Medio, FPI, Certificado de Profesionalidad de Nivel 2 en otra especialidad')),
    (8, _('Ciclo de Grado Superior, FPII; Certificado de Profesionalidad de Nivel 3 en otra especialidad')),
)

NIVELES_IDIOMAS = (
    (1, _('Cero')),
    (2, _('Inicial')),
    (3, _('Intermedio')),
    (4, _('Avanzado')),
)

class Curso(models.Model):
	name = models.CharField(max_length=50)
	matricula_abierta = models.BooleanField(_('Matricula Abierta'),default=datetime.date.today)
	def __unicode__(self):
		return u"Curso de %s"%(self.name)
	

#Asbtract model to inherit from him
class Registration2019(models.Model):
	password = models.CharField(_('Password'),max_length=6,blank=True,editable=False)
	registration_date = models.DateField(auto_now_add=True)
	curso = models.CharField(_('Elige un curso (*)'),max_length=25, choices=CURSOS_2019)
	name = models.CharField(_('Nombre (*)'),max_length=50)
	surname = models.CharField(_('Apellido(s) (*)'),max_length=100)
	#~ address = models.CharField(_('Address'),max_length=100)
	#~ location = models.CharField(_('Location'),max_length=100)
	#~ postal_code = models.DecimalField(_('Postal Code'),max_digits=6, decimal_places=0)
	#~ sex = models.DecimalField(_('Sex'),max_digits=1, decimal_places=0,choices=SEXO)
	birth_date = models.DateField(_('Fecha Nacimiento'),help_text=_('Formato: AAAA-MM-DD(año-mes-día)'))
	#dni = models.CharField(max_length=9,blank=True,help_text=_('Introduce el DNI completo con la letra sin espacios ni guiones'))
	telephone = models.CharField('Teléfono (*)',max_length=12)
	#telephone2 = models.CharField('Tel. Móvil (*)',max_length=12)
	email = models.EmailField('Email (*)')
	titulacion = models.DecimalField(_('Titulación (*)'),max_digits=1, decimal_places=0,choices=TITULACION)
	nivel_ingles = models.CharField("En caso de elegir ingles indicar el nivel",max_length=150,default="",blank=True)
	desempleado = models.BooleanField(_('Estás desempleado/a'), default=False,blank=True)
	funcionario = models.BooleanField(_('Eres funcionario/a'),  default=False,blank=True)
	accept_conditions = models.BooleanField(_('Accept the conditions'), help_text=_('You must accept the conditions to register'),default=False,blank=True)
	
	def texto_curso(self):
		return self.get_curso_display
	
	def send_secretaria_mail(self):
		##Para el secretaria
		subject = "[HOBETUZ] nueva solicitud desde la Web"
		payload = {'registration': self}
		
		html_content = render_to_string('hobetuz/detalle2019.html', context=payload, request=None)
		
		message_body = html_content
		##send_mail(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
		msg = EmailMultiAlternatives(subject, message_body, settings.DEFAULT_FROM_EMAIL, ["moebius1984@gmail.com","secretaria@eide.es"])
		msg.attach_alternative(html_content, "text/html")
		msg.send()

	def send_confirmation_email(self):
		##Para el alumno
		subject = "Has solicitado un curso de HOBETUZ en EIDE"
		
		html_content = u"""
<html>
<body>
<div class="well">
    Acaba de realizar una solicitud de curso para: %s 
</div>
<div class="well">
<p>En caso de que convoquemos un curso de los que solicita y cumpla los requisitos, no pondremos en contacto con usted para realizar un proceso de selección.</p>
</div>
</body>
</html>
"""%(self.get_curso_display)
		
		message_body = html_content
		##send_mail(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
		msg = EmailMultiAlternatives(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
		msg.attach_alternative(html_content, "text/html")
		##msg.content_subtype = "html"
		msg.send()
		
		##Para el secretaria
		
		subject = "[HOBETUZ] nueva solicitud desde la Web"
		payload = {'registration': self}
		
		html_content = render_to_string('hobetuz/detalle2019.html', payload)
		
		message_body = html_content
		##send_mail(subject, message_body, settings.DEFAULT_FROM_EMAIL, [self.email])
		msg = EmailMultiAlternatives(subject, message_body, settings.DEFAULT_FROM_EMAIL, ["moebius1984@gmail.com","secretaria@eide.es","ruth.farpon@eide.es","eide@eide.es"])
		msg.attach_alternative(html_content, "text/html")
		##msg.content_subtype = "html"
		msg.send()

	def __unicode__(self):
		return u"%s-%s"%(self.id,self.email)
	
	#def get_detail_url(self):
		#return reverse('hobetuz_view',args=[self.id])
		#return "/hobetuz/view/%d/"%self.id
	
	def registration_name(self):
				return self.__unicode__()
	
	#Antes de guardar ahaceos algunas cosas, como generar password y enviar un mail
	def save(self, *args, **kwargs):
		##We generate a random password
		if self.id is None:
			#We set de password, not used right now
			self.password = ''.join([choice(letters) for i in xrange(6)])
			#We send a confirmation mail to te registrant and a advise mail to the admins
			self.send_secretaria_mail()
			self.send_confirmation_email()
		super(Registration2019, self).save(*args, **kwargs)

class Registration(models.Model):
	curso = models.ForeignKey(Curso,verbose_name="Primera Opción (*)",limit_choices_to = {'matricula_abierta': True})
	curso2 = models.ForeignKey(Curso,verbose_name="Segunda Opción",limit_choices_to = {'matricula_abierta': True},blank=True,related_name="registration2_set",null=True)
	curso3 = models.ForeignKey(Curso,verbose_name="Tercera Opción",limit_choices_to = {'matricula_abierta': True},blank=True,related_name="registration3_set",null=True)
	curso4 = models.ForeignKey(Curso,verbose_name="Cuarta Opción",limit_choices_to = {'matricula_abierta': True},blank=True,related_name="registration4_set",null=True)
	curso5 = models.ForeignKey(Curso,verbose_name="Quinta Opción",limit_choices_to = {'matricula_abierta': True},blank=True,related_name="registration5_set",null=True)

	password = models.CharField(_('Password'),max_length=6,blank=True,editable=False)
	name = models.CharField(_('Nombre (*)'),max_length=50)
	surname = models.CharField(_('Apellido(s) (*)'),max_length=100)
	#~ address = models.CharField(_('Address'),max_length=100)
	#~ location = models.CharField(_('Location'),max_length=100)
	#~ postal_code = models.DecimalField(_('Postal Code'),max_digits=6, decimal_places=0)
	#~ sex = models.DecimalField(_('Sex'),max_digits=1, decimal_places=0,choices=SEXO)
	birth_date = models.DateField(_('Birth Date'),help_text=_('Formato: AAAA-MM-DD(año-mes-día)'))
	#dni = models.CharField(max_length=9,blank=True,help_text=_('Introduce el DNI completo con la letra sin espacios ni guiones'))
	telephone = models.CharField('Tel. Fijo (*)',max_length=12)
	telephone2 = models.CharField('Tel. Móvil (*)',max_length=12)
	email = models.EmailField('Email (*)')
	
	titulacion = models.DecimalField(_('Titulación (*)'),max_digits=1, decimal_places=0,choices=TITULACION)
	
	desempleado = models.BooleanField(_('Desempleado'), help_text=_('haga click en el check si se encuentra en situación de desempleo'))
	fecha_desempleo = models.DateField(default=datetime.date.today, blank=True, null=True,help_text=_('Formato: AAAA-MM-DD(año-mes-día)'))
	
	empresa_nombre = models.CharField(_('Nombre de la empresa'),max_length=100, blank=True)
	empresa_puesto = models.CharField(_('Puesto en la empresa'),max_length=100, blank=True)
	empresa_actividad = models.CharField(_('Actividad de la empresa'),max_length=200, blank=True)
	
	registration_date = models.DateField(auto_now_add=True)
	
	nivel_ingles = models.DecimalField(_('Nivel Ingles'),help_text="En caso de que haya escogido este idioma indique su nivel",max_digits=1, decimal_places=0,choices=NIVELES_IDIOMAS,blank=True,null=True)
	nivel_frances = models.DecimalField(_('Nivel Frances'),help_text="En caso de que haya escogido este idioma indique su nivel",max_digits=1, decimal_places=0,choices=NIVELES_IDIOMAS,blank=True,null=True)
	nivel_aleman = models.DecimalField(_('Nivel Aleman'),help_text="En caso de que haya escogido este idioma indique su nivel",max_digits=1, decimal_places=0,choices=NIVELES_IDIOMAS,blank=True,null=True)

hobetuz/forms.py
# -*- coding: utf-8 -*-

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  


from django import forms
from django.forms import ModelForm
from models import *
from django.forms.models import inlineformset_factory
from django.forms.extras.widgets import SelectDateWidget
from localflavor.es.forms import *
from django.contrib.admin import widgets                                       
from django.utils.translation import gettext_lazy as _

class CursoForm(ModelForm):
	class Meta:
		fields = '__all__'
		model = Curso
		
class RegistrationForm(ModelForm):
	class Meta:
		model = Registration
		fields = '__all__'
	telephone = ESPhoneNumberField(label=_("Teléfono Fijo (*)"))
	telephone2 = ESPhoneNumberField(label=_("Teléfono Móvil (*)"))
	#dni = ESIdentityCardNumberField()
	#~ postal_code = ESPostalCodeField(label=_("Código Postal"))
	#~ class Meta:
		#~ model = Registration
		#~ exclude = ('paid')
	#~ 
	#~ def __init__(self, *args, **kwargs):
		#~ super(ModelForm, self).__init__(*args, **kwargs)
		#~ self.fields['birth_date'].widget.format = '%d-%m-%Y'
#~ 
		#~ # at the same time, set the input format on the date field like you want it:
		#~ self.fields['birth_date'].input_formats = ['%d-%m-%Y']	

class Registration2019Form(ModelForm):
	class Meta:
		model = Registration2019
		fields = '__all__'
	telephone = ESPhoneNumberField(label=_("Teléfono (*)"))
	#curso = forms.MultipleChoiceField(choices=CURSOS_2019, widget=forms.CheckboxSelectMultiple())

#~ class RegistrationEditForm(ModelForm):
	#~ telephone = ESPhoneNumberField(label=_("Teléfono"))
	#~ #dni = ESIdentityCardNumberField()
	#~ postal_code = ESPostalCodeField(label=_("Código Postal"))
	#~ class Meta:
		#~ model = Registration
	#~ def __init__(self, *args, **kwargs):
		#~ super(ModelForm, self).__init__(*args, **kwargs)
		#~ self.fields['birth_date'].widget.format = '%d-%m-%Y'
#~ 
		#~ # at the same time, set the input format on the date field like you want it:
		#~ self.fields['birth_date'].input_formats = ['%d-%m-%Y']

hobetuz/templates/hobetuz/detalle.html
{% extends "site_base.html"%}

{% load i18n %}

{% block body %}

<h1>Solicitud Hobetuz {{ registration.surname }},{{ registration.name }}</h1>
<h2>Datos de Contacto</h2>
<table class="table">
	<tr>
		<td><b>Nombre</b></td><td>{{ registration.name }}</td>
	
		<td><b>Apellidos</b></td><td>{{ registration.surname }}</td>
	</tr>
	<tr>
		<td><b>Teléfono Fijo</b></td><td>{{ registration.telephone }}</td>
		<td><b>Teléfono Móvil</b></td><td>{{ registration.telephone2 }}</td>
	</tr>
	<tr>
		<td><b>e-mail</b></td><td>{{ registration.email }}</td>
	
		<td><b>Fecha Solicitud</b></td><td>{{ registration.registration_date }}</td>
	</tr>
	</table>

<h2>Datos laborales</h2>
<table class="table">
	<tr>
		<td>Desempleado</td><td>{%if registration.desempleado %} Sí {% else  %} No {% endif %} </td>  {% if registration.desempleado %} <td>fecha</td><td>{{ registration.fecha_desempleo|date:"c" }}</td>{% else%}<td></td><td></td>{% endif %}<td></td><td></td>
	</tr>
	<tr>
		<td>Empresa</td><td>{% if registration.empresa_nombre %}{{ registration.empresa_nombre }}{% endif %}</td>
		<td>Puesto</td><td>{% if registration.empresa_puesto %}{{ registration.empresa_puesto }}{% endif %}</td>
		<td>Actividad</td><td>{% if registration.empresa_actividad %}{{ registration.empresa_actividad }}{% endif %}</td>
	</tr>
</table>
<h2>Solicitud</h2>
<table class="table">
	<tr>
		<td  ><b>Primera Opción</td><td  >{{ registration.curso }}</td>
	</tr>
	<tr>
		<td ><b>Segunda Opción</b></td><td >{{ registration.curso2 }}</td>
	</tr>
	<tr>
		<td ><b>Terecera Opción</b></td><td >{{ registration.curso3 }}</td>
	</tr>
	<tr>
		<td ><b>Cuarta Opción</b></td><td >{{ registration.curso4 }}</td>
	</tr>
	<tr>
		<td ><b>Quinta Opción</b></td><td >{{ registration.curso5 }}</td>
	</tr>
</table>

<h2>Niveles idiomas</h2>
<table class="table">
	<thead>
		<th></th><th>Inglés</th><th>Frances</th><th>Aleman</th><th>Chino</th>
	</thead>
	<tbody>
		<tr>
			<td><b>Nivel</b></td>
			<td>{{ registration.get_nivel_ingles_display }}</td>
			<td>{{ registration.get_nivel_frances_display }}</td>
			<td>{{ registration.get_nivel_aleman_display }}</td>
			<td>{{ registration.get_nivel_chino_display }}</td>
		</tr>
	</tbody>
</table>

<button class="btn primary" onclick="myFunction()">Imprimir</button>

<script>
function myFunction() {
    window.print();
}
</script>

{% endblock %}

hobetuz/templates/hobetuz/detalle2019.html
{% extends "site_base_clean.html"%}

{% load i18n %}

{% block body %}

<h1>Solicitud Hobetuz {{ registration.surname }},{{ registration.name }}</h1>
<h2>Datos de Contacto</h2>
<table class="table">
	<tr>
		<td><b>Nombre</b></td><td>{{ registration.name }}</td>
	
		<td><b>Apellidos</b></td><td>{{ registration.surname }}</td>
	</tr>
	<tr>
		<td><b>Teléfono</b></td><td>{{ registration.telephone }}</td>
		<td><b>Fecha Nac.</b></td><td>{{ registration.bith_date }}</td>
	</tr>
	<tr>
		<td><b>e-mail</b></td><td>{{ registration.email }}</td>
	
		<td><b>Fecha Solicitud</b></td><td>{{ registration.registration_date }}</td>
	</tr>
	</table>

<h2>Datos laborales</h2>
<table class="table">
	<tr>
		<td>Desempleado</td><td>{%if registration.desempleado %} Sí {% else  %} No {% endif %} </td>  
	</tr>
	<tr>
		<td>Funcionario</td><td>{%if registration.funcionaio %} Sí {% else  %} No {% endif %} </td>  
	</tr>
</table>
<h2>Solicitud</h2>
<table class="table">
	<tr>
		<td><b>Curso</td><td  >{{ registration.get_curso_display }}</td>
	</tr>
	<tr>
		<td ><b>Titulación</b></td><td >{{ registration.get_titulacion_display }}</td>
	</tr>
	<tr>
		<td ><b>Nivel de Ingles</b></td><td >{{ registration.nivel_ingles }}</td>
	</tr>
</table>

<button class="btn primary" onclick="myFunction()">Imprimir</button>

<script>
function myFunction() {
    window.print();
}
</script>

{% endblock %}

hobetuz/templates/hobetuz/registration_form.html
{% extends "site_base.html"%}
{% load i18n %}
{% load bootstrap %}

{% block extra_body %}

<script>
	function comprobar_aceptacion() {
		console.log("Comprobamos de las condiciones");
		acepta = false;
		if ($("#id_accept_conditions").is(":checked"))
		{
		    console.log("Condiciones generales aceptadas");
			acepta = true;
		}
		if (acepta) {
		    console.log("Dice que las acepta");
		    $("#send_form").prop('disabled', false);
		    console.log("Ocultamos el aviso");
		    $("#aviso_condiciones").hide();
		}else {
		    //Deshabilitamos el envio hasta que acepten las condiciones
			console.log("Dice que NO las acepta");
			$("#send_form").prop('disabled', true);
		    console.log("Mostramos el aviso");
		    $("#aviso_condiciones").show();
		}
    }
	function comprobar_desempleado() {
		console.log("Han hecho click en el check de desempleado");
		if ($("#id_desempleado").is(":checked")) {
			console.log("Dice que esta desempleado");
			
			$("#id_fecha_desempleo").prop('disabled', false);
			
			$("#id_empresa_nombre").prop('disabled', true);
			$("#id_empresa_puesto").prop('disabled', true);
			$("#id_empresa_actividad").prop('disabled', true);
			
	    
	   }else {
			//Deshabilitamos el envio hasta que acepten las condiciones
			console.log("Dice que NO está desempleado");
			$("#id_fecha_desempleo").prop('disabled', true);
			
			$("#id_empresa_nombre").prop('disabled', false);
			$("#id_empresa_puesto").prop('disabled', false);
			$("#id_empresa_actividad").prop('disabled', false);
			
					
		}
	};
	$(document).ready(function() {
		//$("#id_birth_date").datepicker({format: "yyyy-mm-dd",weekStart: 1});
		$("#normativa_general").hide();
		//comprobar_desempleado();
		//$("#id_desempleado").change(comprobar_desempleado);
		//Control de la aceptación de las condiciones:
		comprobar_aceptacion();
		$("#id_accept_conditions").change(comprobar_aceptacion);
		
            
	});            
</script>

{% endblock%}

{% block body %}

<h1>{% trans "Solicita un curso de Hobetuz" %}</h1>


<div class="alert-mesagge block-message alert">
<p>
Le informamos conforme a lo previsto en el RGPD de 27 de abril de 2016 que ESCUELAS INTERNACIONALES PARA LA EDUCACIÓN Y EL DESARROLLO EIDE S.L., recaba y trata sus datos de carácter personal, aplicando las medidas técnicas y organizativas que garantizan su confidencialidad, con la finalidad de gestionar la relación que le vincula. Usted da su consentimiento y autorización para dicho tratamiento. Conservaremos sus datos de carácter personal únicamente el tiempo imprescindible para gestionar nuestra relación. Podrá ejercitar los derechos de acceso, rectificación, supresión, limitación, portabilidad y oposición dirigiéndose a ESCUELAS INTERNACIONALES PARA LA EDUCACIÓN Y EL DESARROLLO EIDE S.L. con dirección Genaro Oraá Kalea 6,Santurce,48980,BIZKAIA.
</p>
</div>

<div class="alert-mesagge block-message alert">
<p>Si desea solicitar un curso de Hobetuz en EIDE, por favor, indíquenos los datos que le indicamos a continuación. Esta solicitud no implica que vaya a ser seleccionado. En caso de que convoquemos un curso de los que solicita y cumpla los requisitos, no pondremos en contacto con usted para realizar un proceso de selección.</p>
<p>Los campos con un (*) con oblitarios el resto son opcionales</p>
</div>

<div class="row">
    <div class="span14">
		
	<form action="" method="post" class="form-horizontal" >{% csrf_token %}
	{{ form|bootstrap }}
    </div> 
</div>

<div class="row">
    <div class="span12">    
	<div class="well" id="aviso_condiciones">
	    {% trans "<b>¡Atención!.</b> Todavía no ha aceptado las condiciones. Si no acepta las condiciones generales no podrá enviar la matrícula." %}
	</div>
	<input id="send_form" class="btn primary pull-right" type="submit" value="{% trans 'Submit' %}" />
    </div> 
</div> 

{% endblock %}